/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>

#define PLUGIN "[ZP] Round Start Low Gravity"
#define VERSION "1.0"
#define AUTHOR "O'Zone"

public plugin_init()
{
	register_plugin(PLUGIN, VERSION, AUTHOR);
	
	register_logevent("gravity_on", 2, "1=Round_Start");
}

public gravity_on()
{
	set_cvar_num("sv_gravity", 250);
	set_task(15.0, "gravity_off");
}

public gravity_off()
	set_cvar_num("sv_gravity", 800);