
#if defined _amxmodx_version_included
  #endinput
#endif
#define _amxmodx_version_included

#define AMXX_VERSION_TAG        "dev"
#define AMXX_VERSION_CSET       "2d049b7"
#define AMXX_VERSION_MAJOR      "1"
#define AMXX_VERSION_MINOR      "8"
#define AMXX_VERSION_RELEASE    "3"
#define AMXX_VERSION_LOCAL_REV  "5109"
#define AMXX_VERSION            1.83
#define AMXX_VERSION_NUM        183

stock const AMXX_VERSION_STR[] = "1.8.3-dev+5109";
    