#if defined _shop_sms_const_included
	#endinput
#endif
#define _shop_sms_const_included

#pragma library "shop_sms_const"

#define VERSION "3.3.7"

#define SS_OK -1
#define SS_ERROR -2
#define SS_STOP -3
#define SS_BAD_ARGS -4

#define MAX_ID 32

#define TYPE_NICK 1<<0
#define TYPE_IP 1<<1
#define TYPE_SID 1<<2
#define TYPE_SID2 1<<3

#define ADMIN_FLAG_V (1<<21)
#define ADMIN_FLAG_W (1<<22)
#define ADMIN_FLAG_X (1<<23)
