/*
 * Weapons Library for ZP Level System
 *
 * @param id        Player index.
*/
native give_weapon_balrog5(id)

native give_cso_cart_blue(id)

native give_weapon_ak47long(id)

native give_kriss(id, drop)

native give_weapon_qbz95b(id)

native give_weapon_anaconda(id)

native give_weapon_inf(id)

native give_dinfinity(id)

native give_weapon_skull1(id)

native give_weapon_sl8ex(id)

native give_weapon_skull5(id, drop)

native give_weapon_usas(id)

native give_weapon_dbarrel(id, drop)

native give_weapon_guitar1(id, drop)

native give_weapon_plasmagun(id, drop)

native give_weapon_m134ex(id)

native give_weapon_sfmg(id, drop)